version: '3'

services:
  client:
    image: jacobmoxham2/part_ii_project_implementation:im-client-no-mware
    ports:
      - "4000:4000"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.2'
          memory: 200M
  server:
    image: jacobmoxham2/part_ii_project_implementation:im-server-no-mware
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 1G