version: '3'

services:
  data-client:
    build: './data-client'
  database:
    image: mysql
    container_name: database.dev
    command: mysqld --user=root --verbose
    volumes:
      - ./mysql-init/dbcreation.sql:/tmp/dbcreation.sql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: power_consumption
      MYSQL_USER: "demouser"
      MYSQL_PASSWORD: "demopassword"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  requesting-client:
    build: './requesting-client'
    ports:
      - "4000:4000"
      - "6060:6060"
  server:
    build: './server'