version: '3'

services:
  client:
    image: jacobmoxham2/part_ii_project_implementation:im-client
    command: '-image-filename 9kB.jpg'
    ports:
      - "4000:4000"
    deploy:
      resources:
        limits:
          cpus: '0.09'
          memory: 50M
        reservations:
          cpus: '0.09'
          memory: 50M
  server:
    image: jacobmoxham2/part_ii_project_implementation:im-server
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: 2G
        reservations:
          cpus: '0.1'
          memory: 2G