version: '3'

services:
  data-client-raw-data:
    build: './data-client-configurable'
    command: -raw-data database-raw-data
    container_name: data-client-raw-data
  data-client-can-compute:
    build: './data-client-configurable'
    command: -can-compute database-can-compute
    container_name: data-client-compute
  data-client-both:
    build: './data-client-configurable'
    command: -raw-data -can-compute database-both
    container_name: data-client-both
  data-client-no-computation:
    build: './data-client-configurable'
    container_name: data-client-none
  database-both:
    image: mysql
    container_name: database-both
    command: mysqld --user=root --verbose
    volumes:
      - ./mysql-init/dbcreation.sql:/tmp/dbcreation.sql
      - ./mysql-init:/docker-entrypoint-initdb.d
#    ports:
#      - "3306:3306"
    environment:
      MYSQL_DATABASE: power_consumption
      MYSQL_USER: "demouser"
      MYSQL_PASSWORD: "demopassword"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  database-raw-data:
    image: mysql
    container_name: database-raw-data
    command: mysqld --user=root --verbose
    volumes:
      - ./mysql-init/dbcreation.sql:/tmp/dbcreation.sql
      - ./mysql-init:/docker-entrypoint-initdb.d
  #  ports:
  #    - "3306:3306"
    environment:
      MYSQL_DATABASE: power_consumption
      MYSQL_USER: "demouser"
      MYSQL_PASSWORD: "demopassword"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  database-can-compute:
    image: mysql
    container_name: database-can-compute
    command: mysqld --user=root --verbose
    volumes:
      - ./mysql-init/dbcreation.sql:/tmp/dbcreation.sql
      - ./mysql-init:/docker-entrypoint-initdb.d
  #  ports:
  #    - "3306:3306"
    environment:
      MYSQL_DATABASE: power_consumption
      MYSQL_USER: "demouser"
      MYSQL_PASSWORD: "demopassword"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  requesting-client:
    build: './requesting-client'
    ports:
      - "4000:4000"
      - "6060:6060"
  server:
    build: './server'
#    command: data-client-raw-data data-client-no-computation
    ports:
      - "3002:3002"